# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: orangerouter
email: ngquanhao@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A computer science student on the journey of becoming a better engineer and human being.

domain: "orangeng.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://orangeng.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  orangeng

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
